name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar repositorio
        uses: actions/checkout@v4

      - name: 🟢 Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 🔵 BACKEND
      - name: 📦 Instalar backend
        run: |
          cd backend
          npm install

      - name: ⚙️ Prisma generate
        run: |
          cd backend
          npx prisma generate

      - name: 🧪 Test backend
        run: |
          cd backend
          npm test

      # 🟣 FRONTEND
      - name: 📦 Instalar frontend
        run: |
          cd frontend
          npm install

      - name: 🏗️ Build frontend
        run: |
          cd frontend
          npm run build

      # 🚀 START BACKEND
      - name: ▶️ Start backend
        run: |
          cd backend
          npm run dev &

      # 🚀 START FRONTEND
      - name: ▶️ Start frontend
        run: |
          cd frontend
          npm run preview &

      # ⏳ Esperar servicios
      - name: ⏳ Wait services
        run: sleep 8

      # 🎭 PLAYWRIGHT
      - name: 🎭 Instalar Playwright
        run: |
          cd frontend
          npx playwright install

      - name: 🧪 Run E2E tests
        run: |
          cd frontend
          npm run test:e2e